### ISSUE TITLE
Add more chart types?

### ISSUE THREAD

**Issue by Sweeper777** [gpbl/SwiftChart#48]
I have used a lot of chart pods but none of them is as easy to use as this one. It would be really good if more chart types are supported. Maybe add a bar chart?

**Comment by gpbl** [comment]
Thanks for the nice feedback! 

As this library already covers my needs, I'm not so keen to implement other chart types. My feeling is that other libraries are harder to use because they want to do too much.

However we can start discussing about bars. For example, 
What would be the requirements, 
which the customizable parts, 
where the possible issues (e.g. widths/spacing)?

**Comment by Sweeper777** [comment]
I don't think that's the reason why other libraries are hard to use. The widths and spacings can have default values and if users want, they can set them themselves, can't they?

**Comment by gpbl** [comment]
Sure it is possible - however we need a different class to draw the bars and add different options. This will for sure add more complexity to the API. I don't have the time ATM to add this 😔

**Comment by gpbl** [comment]
I'm closing this since I won't add new chart type anytime soon. I prefer to improve the current ones 👍
