### ISSUE TITLE
Ignore values

### ISSUE THREAD

**Issue by 9SL9** [gpbl/SwiftChart#66]
I have an array with default values of -1 in each element - the code I have will change some of this based on events in the app. How do I only display the updated values and have SwiftChart ignore values below 0?

**Comment by gpbl** [comment]
To update the series:

- remove the old series
- add the updated one
- call `setNeedsDisplay` to refresh the chart

I should add a `reload` method or something... 

> and have SwiftChart ignore values below 0?

what do you mean for _ignore_? Couldn't you just pass a series without those values in it?

**Comment by 9SL9** [comment]
Basically my array (after processing) will look like:
[-1.0, -1.0, 1.5, 10.3, -1.0, -1.0]

The outcome I'm after is for on values above '0' to be drawn in the chart. What would be the best way to accomplish this? I'd prefer for the chart to simply be blank where there is a -1.0.

I hope that makes more sense :)

**Comment by gpbl** [comment]
@9SL9 if I understand correctly, you need to "interrupt" the line. I'm not sure if it is possible with one series. I was trying splitting the series in multiple series (e.g. each one you meet a -1, just create a new series):

```swift
let data1 = [(x: 1.0, y: 0), (x: 2, y: 3.1), (x: 3, y: 2), (x: 4, y: -4.2)];
let series1 = ChartSeries(data: data1)
series1.color = ChartColors.purpleColor()

let data2 = [(x: 6.0, y: 0), (x: 7, y: 3.1), (x: 8, y: 2)];
let series2 = ChartSeries(data: data2)
series2.color = ChartColors.purpleColor()

let data3 = [(x: 10.0, y: 3.0), (x: 11.0, y: 2), (x: 12.0, y: 5)];
let series3 = ChartSeries(data: data3)
series3.color = ChartColors.purpleColor()

chart.add([series1, series2, series3])
```

but the result is not as expected since it expects the first series telling about all the x-values:

<img width="300" alt="screen shot 2017-05-20 at 12 26 24" src="https://cloud.githubusercontent.com/assets/120693/26278011/b066a516-3d57-11e7-92e0-6645f1fbba59.png">

So if I add a series with a clear color and _all the x values_:

```diff
+ let series0 = ChartSeries([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
+ series0.color = UIColor.clear
// snip
- chart.add([series1, series2, series3])
+ chart.add([series0, series1, series2, series3])
```

it works better:

<img width="302" alt="screen shot 2017-05-20 at 12 33 44" src="https://cloud.githubusercontent.com/assets/120693/26278052/9d0b38be-3d58-11e7-9aaa-cda0f3cccb50.png">

Would it work as workaround?

**Comment by gpbl** [comment]
Closing as answered 🤔
