### ISSUE TITLE
adjust chart height so that vertical labels can be seen

### ISSUE THREAD

**Issue by Sweeper777** [gpbl/SwiftChart#67]
This is what it looks like if I used long x axis labels:

<img width="313" alt="2017-05-22 7 33 40" src="https://cloud.githubusercontent.com/assets/13585047/26295329/40852202-3ec1-11e7-9f4f-6b11f698d3cc.png">

It is supposed to be like `20/05` instead of `20/0` with the last character being cut off.

Is there a way to make the chart shorter so as to accommodate the x labels? Or calculate the font size at which the x labels will not be truncated?

**Comment by gpbl** [comment]
They must be cut out from the view – could you try to add some padding at the bottom? The issue is that labels are placed after the chart frame has been set. In the UI hierarchy, the issue is more clear:

<img width="446" alt="screen shot 2017-05-22 at 21 43 37" src="https://cloud.githubusercontent.com/assets/120693/26336397/d5a13da0-3f37-11e7-80dc-d20effa614b4.png">

the chart's frame (light blue) displays the labels overflowing. I believe your labels are being hidden by the view below the chart.

**Comment by gpbl** [comment]
Tracking this in #69 – thanks for the report!
